### ISSUE TITLE
the channel number of fc in generator is not correct without vae

### ISSUE THREAD

**Issue by wenhuach** [xh-liu/CC-FPSE#1]
self.fc = nn.Conv2d(self.opt.semantic_nc, 16*nf*self.sw*self.sh, 3, padding=1)
=>self.fc = nn.Conv2d(self.opt.semantic_nc, 16 * nf, 3, padding=1)

**Comment by xh-liu** [comment]
Thanks for pointing out the typo! I have fixed it.
