### ISSUE TITLE
How important is the perceptual loss?

### ISSUE THREAD

**Issue by bearcatt** [xh-liu/CC-FPSE#8]
Hi @xh-liu, thanks for the awesome work. 
I found that the perceptual loss cannot decrease during training, which has also been found in  [original GauGAN](https://github.com/NVlabs/SPADE/issues/38).  I am wondering whether this loss is useful or not?  Have you tried not using the perceptual loss for your method?

**Comment by Ha0Tang** [comment]
@bearcatt  Do you know how to train on 8 GPUs?

**Comment by xh-liu** [comment]
@bearcatt Yes, it is normal that the perceptual loss does not decrease during training. But it is important for training. Without the perceptual loss the model will have difficulty in convergence.
